### ISSUE TITLE
Guia para Hooks

### ISSUE THREAD

**Issue by web-Matheus** [rubenmarcus/guiareact.org#24]
## Guia de Hooks
 O que são Hooks? É uma função especial que permite utilizar state dentro de recursos funcionais (dentro de uma função)
  Como usar?
  Você precisa importar o useState.O useState recebe um argumento que é o valor do estado atual e uma função que permite alterar o estado.
  ```jsx
    import {usestate} from 'react';
    function Counter(){
      const[count,setCount] = useState(0);
    return(
      <>
      <h1>Contador {count}</h1>
      <button
      onClick={()=>setCount(count+1)}
      > adicionar </button>
      </>
    )
  }
  ```
  Explicando o exemplo acima.
   Iniciamos o estado atual com zero, e para mudar esse estado toda vez que o usuário clicar no butão devemos fazer isso com a funcão SetCount que adiciona 1 toda vez que o usuário invoca a função.

**Comment by rubenmarcus** [comment]
Esse exemplo está com import errado do useState, vamos criar uma branch modelo pro Guia de Hooks em breve, ai pode contribuir
