### ISSUE TITLE
feat: context api

### ISSUE THREAD

**Issue by taisesoares** [rubenmarcus/guiareact.org#31]
Descrição sobre context API.
https://github.com/rubenmarcus/guiareact.org/pull/30

**Comment by taisesoares** [comment]
Alguém comentário ou melhoria para realizarmos o merge ?

**Comment by rubenmarcus** [comment]
@taisesoares  vou trabalhar numa nova versão do site e ai terá uma sessão a parte só para isso. obrigado!
